/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ModelDao.DaoUser;
import ModelDao.Table;
import conection.ConexaoBanco;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelBeans.ModelUser;

/**
 *
 * @author kasil
 */
public class CadastroUsuario extends javax.swing.JFrame {

    ModelUser mod = new ModelUser();
    DaoUser dao = new DaoUser();
    //ModelUser user = new ModelUser();
    ConexaoBanco conecte = new ConexaoBanco();
    int flag = 0;
    
    public CadastroUsuario() {
        initComponents();
        atualizarTabela("select *from caduser order by nome_user");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelMedico3 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabelcpf = new javax.swing.JLabel();
        jFormattedCpf = new javax.swing.JFormattedTextField();
        jPasswordConfirme = new javax.swing.JPasswordField();
        jLabelSenha = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jTextFieldID = new javax.swing.JTextField();
        jLabelSenha1 = new javax.swing.JLabel();
        jLabelcpf1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jLabelSenha2 = new javax.swing.JLabel();
        quadro = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 630, -1));

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, -1));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, -1, -1));

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, -1, -1));

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cadastro de Usuário.png"))); // NOI18N
        jLabel1.setToolTipText("Cadastro de Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        jLabelMedico3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMedico3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMedico3.setText("Nome:");
        getContentPane().add(jLabelMedico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jTextNome.setEnabled(false);
        getContentPane().add(jTextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 220, -1));

        jLabelcpf.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcpf.setText("CPF:");
        getContentPane().add(jLabelcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        try {
            jFormattedCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedCpf.setEnabled(false);
        getContentPane().add(jFormattedCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 150, -1));

        jPasswordConfirme.setEnabled(false);
        getContentPane().add(jPasswordConfirme, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 210, -1));

        jLabelSenha.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Confirme sua senha:");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, -1, -1));

        jPassword.setEnabled(false);
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 210, -1));

        jTextFieldID.setEnabled(false);
        getContentPane().add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 30, -1));

        jLabelSenha1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSenha1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha1.setText("Senha:");
        getContentPane().add(jLabelSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        jLabelcpf1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcpf1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcpf1.setText("ID:");
        getContentPane().add(jLabelcpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Recepcionista" }));
        jComboBox1.setEnabled(false);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 140, -1));

        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUser);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 740, 140));

        jLabelSenha2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSenha2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha2.setText("Tipo:");
        getContentPane().add(jLabelSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, -1, 20));

        quadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Rectangle 49_1.png"))); // NOI18N
        getContentPane().add(quadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Desktop - 19.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 740));

        setSize(new java.awt.Dimension(1380, 769));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        //se o usuario quer realmente excluir
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setId_user(Integer.parseInt(jTextFieldID.getText()));
            dao.Excluir(mod);
            atualizarTabela("select *from caduser order by nome_user");
        
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextNome.setEnabled(!true);//ativa os campos
        jComboBox1.setEnabled(!true);
        jPassword.setEnabled(!true);
        jPasswordConfirme.setEnabled(!true);
        jFormattedCpf.setEnabled(!true);

        
        jButtonSalvar.setEnabled(!true);//desativa o botao de salvar
        jButtonCancelar.setEnabled(!true);
        
        jButtonNovo.setEnabled(true);
        
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextFieldID.setText("");
        jTextNome.setText("");
        jPassword.setText("");//limpa os campos
        jPasswordConfirme.setText("");
        jTextFieldPesquisar.setText("");

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag = 2;
        jTextNome.setEnabled(true);//ativa os campos
        jComboBox1.setEnabled(true);
        jPassword.setEnabled(true);
        jPasswordConfirme.setEnabled(true);
        jFormattedCpf.setEnabled(true);
        
        
        jButtonSalvar.setEnabled(true);//ativa o botao de salvar
        jButtonCancelar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        
        atualizarTabela("select *from caduser order by nome_user");
        
       // jFormattedCrm.setText("");
        
        
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextNome.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o nome para continuar");// se for vazio avisará
           jTextNome.requestFocus(); // para usuario ver o campo q falta
        }else if(jFormattedCpf.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha seu CPF para continuar");
           jFormattedCpf.requestFocus();
        }else if(jPassword.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha sua senha para continuar");
           jPassword.requestFocus();
        }else if(jPasswordConfirme.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Confirme sua senha para continuar");
           jPasswordConfirme.requestFocus();

        }else
        if(flag == 1){
            mod.setNome(jTextNome.getText());
            mod.setTipo((String) jComboBox1.getSelectedItem());
            mod.setCpf(jFormattedCpf.getText());
            mod.setSenha(jPassword.getText());
            
            dao.Salvar(mod);
            
            jTextNome.setText("");
            jPassword.setText("");//limpa os campos
            jPasswordConfirme.setText("");
            jFormattedCpf.setText("");
            
            jTextNome.setEnabled(false);
            jPassword.setEnabled(false);
            jPasswordConfirme.setEnabled(false);//desativa os campos
            jFormattedCpf.setEnabled(false);
            jComboBox1.setEnabled(false);
            
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);

            atualizarTabela("select *from caduser order by nome_user");
             
       }else{
            mod.setId_user(Integer.parseInt(jTextFieldID.getText()));
            mod.setNome(jTextNome.getText());
            mod.setTipo((String) jComboBox1.getSelectedItem());
            mod.setCpf(jFormattedCpf.getText());
            mod.setSenha(jPassword.getText());
            
            dao.Alterar(mod);
            
            jTextFieldID.setText("");
            jTextNome.setText("");
            jPassword.setText("");//limpa os campos
            jPasswordConfirme.setText("");
            jFormattedCpf.setText("");
            
            jTextNome.setEnabled(false);
            jPassword.setEnabled(false);
            jPasswordConfirme.setEnabled(false);//desativa os campos
            jFormattedCpf.setEnabled(false);
            jComboBox1.setEnabled(false);
            
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);

            atualizarTabela("select *from caduser order by nome_user");     
           
       }
       
       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        
        jTextNome.setEnabled(true);
        jFormattedCpf.setEnabled(true);
        jComboBox1.setEnabled(true);
        jPassword.setEnabled(true);
        jPasswordConfirme.setEnabled(true);
        
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldPesquisar.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        
       // atualizarTabela("select *from caduser order by nome_user");
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUserMouseClicked
        String nomeUser = ""+jTableUser.getValueAt(jTableUser.getSelectedRow(),1);//oq for selecionado e vai colocar na string
        conecte.conexao();
        conecte.executaSql("select *from caduser where nome_user ='"+nomeUser+"'");
        try {
 
            if(conecte.rs.first()){//vai pegar o primeiro clique e vai verificar se é depois verifcar no banco se realmente tem esses dados
                
                jTextFieldID.setText(String.valueOf(conecte.rs.getInt("id_user")));
                jTextNome.setText(conecte.rs.getString("nome_user"));
                jFormattedCpf.setText(conecte.rs.getString("cpf"));
                jComboBox1.setSelectedItem(conecte.rs.getString("tipo"));
                jPassword.setText(conecte.rs.getString("senha"));
                jPasswordConfirme.setText(conecte.rs.getString("senha"));
                //jPasswordConfirme.setText(conecte.rs.getString("login_id"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar o dado"+ex);//caso de erro aparece uma mensagem
        }
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(true);//habilita botoes
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jTextFieldID.setEnabled(false);
        jTextNome.setEnabled(false);
        jPassword.setEnabled(false); 
        jPasswordConfirme.setEnabled(false);
        jComboBox1.setEnabled(false);
        conecte.desconecta();
    }//GEN-LAST:event_jTableUserMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisa(jTextFieldPesquisar.getText());
        ModelUser model = dao.pesquisar(mod);

        jTextFieldID.setText(String.valueOf(model.getId_user()));
        jTextNome.setText(model.getNome());
        jFormattedCpf.setText(model.getCpf());
        jPassword.setText(model.getSenha());
        jPasswordConfirme.setText(model.getSenha());
        jComboBox1.setSelectedItem(model.getTipo());

        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        atualizarTabela("select *from caduser where nome_user like'%" + mod.getPesquisa()+"%'");

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed

        // jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    public void atualizarTabela(String SQL){
        //dados = new ArrayList(); 
        ArrayList dados = new ArrayList();      
        String[] Colunas = new String[]{"ID","Nome","CPF", "Tipo"};//nome das colunas
        
        conecte.conexao();
        conecte.executaSql(SQL);
        
        try {
            conecte.rs.first();
             do{
                 dados.add(new Object[]{
                     
                     conecte.rs.getString("id_user"),
                     conecte.rs.getString("nome_user"),//pega do banco
                     conecte.rs.getString("cpf"),
                     conecte.rs.getString("tipo")
                     
                 });
            }while(conecte.rs.next());//quando passar para o proximo para
             
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"Verifique se escreveu corretamente");
        }
        
        Table tab = new Table(dados, Colunas);

        jTableUser.setModel(tab);
        jTableUser.getColumnModel().getColumn(0).setPreferredWidth(230);
        jTableUser.getColumnModel().getColumn(0).setResizable(false);
        jTableUser.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableUser.getColumnModel().getColumn(1).setResizable(false);
        jTableUser.getColumnModel().getColumn(2).setPreferredWidth(135);
        jTableUser.getColumnModel().getColumn(2).setResizable(false);
        jTableUser.getColumnModel().getColumn(3).setPreferredWidth(170);
        jTableUser.getColumnModel().getColumn(3).setResizable(false);

        jTableUser.getTableHeader().setReorderingAllowed(false);//não vai poder reorganizar as ordem das colunas
        jTableUser.setAutoResizeMode(jTableUser.AUTO_RESIZE_OFF);//O usuario não vai poder modificar o tamanho da tabela
        jTableUser.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//so vai poder selecionar um dado por vez

        conecte.desconecta();

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMedico3;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSenha1;
    private javax.swing.JLabel jLabelSenha2;
    private javax.swing.JLabel jLabelcpf;
    private javax.swing.JLabel jLabelcpf1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JPasswordField jPasswordConfirme;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JLabel quadro;
    // End of variables declaration//GEN-END:variables
}
