/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ModelDao.DaoMedico;
import ModelDao.DaoPac;
import ModelDao.DaoUser;
import ModelDao.Table;
import conection.ConexaoBanco;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelBeans.ModelMed;
import modelBeans.ModelPac;
import modelBeans.ModelUser;

/**
 *
 * @author kasil
 */
public class CadastroPacient extends javax.swing.JFrame {

    ModelPac mod = new ModelPac();
    DaoPac dao = new DaoPac();
    //ModelUser user = new ModelUser();
    ConexaoBanco conecte = new ConexaoBanco();
    int flag = 0;
    
    public CadastroPacient() {
        initComponents();
        preencherNome();
        
        atualizarTabela("select id_pac, nome_pac, cpf_pac,idade_pac,telefone_pac,bairro from paciente inner join endereco on id_end=id_endereco order by nome_pac");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelMedico3 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jLabelcpf = new javax.swing.JLabel();
        jFormattedCpf = new javax.swing.JFormattedTextField();
        jTextFieldID = new javax.swing.JTextField();
        jLabelcpf1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePac = new javax.swing.JTable();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jTextFieldIdade = new javax.swing.JTextField();
        jLabelSenha3 = new javax.swing.JLabel();
        jLabelMedico4 = new javax.swing.JLabel();
        jLabelSenha4 = new javax.swing.JLabel();
        jComboBoxBairro = new javax.swing.JComboBox<>();
        jLabelSenha5 = new javax.swing.JLabel();
        jFormattedTextTelefone = new javax.swing.JFormattedTextField();
        quadro = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 630, -1));

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, -1, -1));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, -1, -1));

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, -1, -1));

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cadastro de Paciente.png"))); // NOI18N
        jLabel1.setToolTipText("Cadastro de Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 420, 70));

        jLabelMedico3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMedico3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMedico3.setText("Nome:");
        getContentPane().add(jLabelMedico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, -1));

        jTextNome.setEnabled(false);
        getContentPane().add(jTextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 190, -1));

        jLabelcpf.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcpf.setText("CPF:");
        getContentPane().add(jLabelcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        try {
            jFormattedCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedCpf.setEnabled(false);
        getContentPane().add(jFormattedCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 150, -1));

        jTextFieldID.setEnabled(false);
        getContentPane().add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 30, -1));

        jLabelcpf1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcpf1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcpf1.setText("ID:");
        getContentPane().add(jLabelcpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jTablePac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePac);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 740, 140));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino\t", "Masculino", "Não-binário" }));
        jComboBoxSexo.setEnabled(false);
        getContentPane().add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, -1));

        jTextFieldIdade.setEnabled(false);
        getContentPane().add(jTextFieldIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 70, -1));

        jLabelSenha3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSenha3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha3.setText("Sexo:");
        getContentPane().add(jLabelSenha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, 20));

        jLabelMedico4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMedico4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMedico4.setText("Telefone");
        getContentPane().add(jLabelMedico4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, -1));

        jLabelSenha4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSenha4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha4.setText("Idade:");
        getContentPane().add(jLabelSenha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, 20));

        jComboBoxBairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBairro.setEnabled(false);
        jComboBoxBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 520, -1));

        jLabelSenha5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSenha5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha5.setText("Endereço:");
        getContentPane().add(jLabelSenha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, 20));

        try {
            jFormattedTextTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextTelefone.setEnabled(false);
        getContentPane().add(jFormattedTextTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 100, -1));

        quadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Rectangle 49_1.png"))); // NOI18N
        getContentPane().add(quadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Desktop - 19.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 740));

        setSize(new java.awt.Dimension(1380, 769));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void preencherNome(){
        conecte.conexao();
        conecte.executaSql("select *from endereco order by bairro");
        try {
            conecte.rs.first();
            jComboBoxBairro.removeAllItems();
            do{
               jComboBoxBairro.addItem(conecte.rs.getString("bairro"));
            }while(conecte.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher bairro"+ex);
        }
        conecte.desconecta();
    }
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
        //se o usuario quer realmente excluir
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setId_pac(Integer.parseInt(jTextFieldID.getText()));
            dao.Excluir(mod);
            
            jTextFieldID.setText("");
            jTextNome.setText("");
            jTextFieldIdade.setText("");//limpa os campos
            jFormattedTextTelefone.setText("");
            jFormattedCpf.setText("");
            jTextFieldPesquisar.setText("");
            atualizarTabela("select id_pac, nome_pac, cpf_pac,idade_pac,telefone_pac,bairro from paciente inner join endereco on id_end=id_endereco order by nome_pac");        
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        /*jTextNome.setEnabled(!true);//ativa os campos
        jComboBox1.setEnabled(!true);
        jPassword.setEnabled(!true);
        jPasswordConfirme.setEnabled(!true);
        jFormattedCpf.setEnabled(!true);*/

        
        jButtonSalvar.setEnabled(!true);//desativa o botao de salvar
        jButtonCancelar.setEnabled(!true);
        
        jButtonNovo.setEnabled(true);
        
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        /*jTextFieldID.setText("");
        jTextNome.setText("");
        jPassword.setText("");//limpa os campos
        jPasswordConfirme.setText("");
        jTextFieldPesquisar.setText("");
*/
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag = 2;
        jTextNome.setEnabled(true);//ativa os campos
        jComboBoxBairro.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jTextFieldIdade.setEnabled(true);
        jFormattedCpf.setEnabled(true);
        jFormattedTextTelefone.setEnabled(true);
        
        
        
        jButtonSalvar.setEnabled(true);//ativa o botao de salvar
        jButtonCancelar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        
        atualizarTabela("select id_pac, nome_pac, cpf_pac,idade_pac,telefone_pac,bairro from paciente inner join endereco on id_end=id_endereco order by nome_pac"); 
        
       // jFormattedCrm.setText("");
        
        
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        
       // jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        
        if(jTextNome.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o nome para continuar");// se for vazio avisará
           jTextNome.requestFocus(); // para usuario ver o campo q falta
        }else if(jFormattedCpf.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha seu CPF para continuar");
           jFormattedCpf.requestFocus();
        }else if(jTextFieldIdade.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha sua idade para continuar");
           jTextFieldIdade.requestFocus();

        }else
        if(flag == 1){
            mod.setNome_pac(jTextNome.getText());
            mod.setIdade(Integer.parseInt(jTextFieldIdade.getText()));
            mod.setTelefone(jFormattedTextTelefone.getText());
            mod.setCpf(jFormattedCpf.getText());
            mod.setSexo((String) jComboBoxSexo.getSelectedItem());
            mod.setNomeBairro((String) jComboBoxBairro.getSelectedItem());
        
            dao.Salvar(mod);
            
            jTextFieldID.setText("");
            jTextNome.setText("");
            jTextFieldIdade.setText("");//limpa os campos
            jFormattedTextTelefone.setText("");
            jFormattedCpf.setText("");
            jTextFieldPesquisar.setText("");
            
            jTextNome.setEnabled(false);
            jTextFieldIdade.setEnabled(false);
            jFormattedTextTelefone.setEnabled(false);//desativa os campos
            jFormattedCpf.setEnabled(false);
            jComboBoxBairro.setEnabled(false);
            
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);

            atualizarTabela("select id_pac, nome_pac, cpf_pac,idade_pac,telefone_pac,bairro from paciente inner join endereco on id_end=id_endereco order by nome_pac");
             
       }else{
            mod.setId_pac(Integer.parseInt(jTextFieldID.getText()));
            mod.setNome_pac(jTextNome.getText());
            mod.setIdade(Integer.parseInt(jTextFieldIdade.getText()));
            mod.setTelefone(jFormattedTextTelefone.getText());
            mod.setCpf(jFormattedCpf.getText());
            mod.setSexo((String) jComboBoxSexo.getSelectedItem());
            mod.setNomeBairro((String) jComboBoxBairro.getSelectedItem());           
            dao.Alterar(mod);
            
            jTextFieldID.setText("");
            jTextNome.setText("");
            jTextFieldIdade.setText("");//limpa os campos
            jFormattedTextTelefone.setText("");
            jFormattedCpf.setText("");
            jTextFieldPesquisar.setText("");
            
            jTextNome.setEnabled(false);
            jTextFieldIdade.setEnabled(false);
            jFormattedTextTelefone.setEnabled(false);//desativa os campos
            jFormattedCpf.setEnabled(false);
            jComboBoxBairro.setEnabled(false);
            jComboBoxSexo.setEnabled(false);
            
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);

            atualizarTabela("select id_pac, nome_pac, cpf_pac,idade_pac,telefone_pac,bairro from paciente inner join endereco on id_end=id_endereco order by nome_pac");     
           
       }
       
       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        
        jTextNome.setEnabled(true);
        jComboBoxBairro.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jFormattedCpf.setEnabled(true);
        jTextFieldIdade.setEnabled(true);
        jFormattedTextTelefone.setEnabled(true);
        
        
        //jButtonAlterar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldPesquisar.setEnabled(true); 
        jButtonPesquisar.setEnabled(true);
        
       
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisar(jTextFieldPesquisar.getText());
        ModelPac model = dao.pesquisar(mod);
        
        jTextFieldID.setText(String.valueOf(model.getId_pac()));
        jTextNome.setText(model.getNome_pac());
        jTextFieldIdade.setText(String.valueOf(model.getIdade()));
        jFormattedCpf.setText(model.getCpf());
        jFormattedTextTelefone.setText(model.getTelefone());
        jComboBoxBairro.setSelectedItem(mod.getNomeBairro());
        jComboBoxSexo.setSelectedItem(mod.getSexo());

        
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);

   
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTablePacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacMouseClicked
        String nomePac = ""+jTablePac.getValueAt(jTablePac.getSelectedRow(),1);//oq for selecionado e vai colocar na string
        conecte.conexao();
        conecte.executaSql("select *from paciente where nome_pac ='"+nomePac+"'");
        try {
 
            if(conecte.rs.first()){//vai pegar o primeiro clique e vai v erificar se é depois verifcar no banco se realmente tem esses dados
                
                jTextFieldID.setText(String.valueOf(conecte.rs.getInt("id_pac")));
                jTextNome.setText(conecte.rs.getString("nome_pac"));
                jTextFieldIdade.setText(String.valueOf(conecte.rs.getInt("idade_pac")));
                jFormattedCpf.setText(conecte.rs.getString("cpf_pac"));
                jFormattedTextTelefone.setText(conecte.rs.getString("telefone_pac"));
                jComboBoxSexo.setSelectedItem(conecte.rs.getString("sexo_pac"));
                jTextFieldIdade.setText(String.valueOf(conecte.rs.getInt("idade_pac")));
                
                //quando se tem chave estrangeira é necessario fazer uma nova conexao selecionando a table dessa chave
                ConexaoBanco conexaoPesquisa = new ConexaoBanco();
                conexaoPesquisa.conexao();
                conexaoPesquisa.executaSql("select *from endereco where id_endereco="+conecte.rs.getInt("id_end"));
                conexaoPesquisa.rs.first();
                jComboBoxBairro.setSelectedItem(conexaoPesquisa.rs.getString("bairro"));
                conexaoPesquisa.desconecta();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar o dado"+ex);//caso de erro aparece uma mensagem
        }
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(true);//habilita botoes
        jButtonExcluir.setEnabled(true); 
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jTextFieldID.setEnabled(false);
        jTextNome.setEnabled(false);
        /*jPassword.setEnabled(false); 
        jPasswordConfirme.setEnabled(false);
        jComboBox1.setEnabled(false);*/

    }//GEN-LAST:event_jTablePacMouseClicked

    private void jComboBoxBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBairroActionPerformed

    public void atualizarTabela(String SQL){
        //dados = new ArrayList(); 
        ArrayList dados = new ArrayList();      
        String[] Colunas = new String[]{"ID","Nome","Idade", "CPF", "Telefone","Bairro"};//nome das colunas
        
        conecte.conexao();
        conecte.executaSql(SQL);
        
        try {
            conecte.rs.first();
             do{
                 dados.add(new Object[]{
                     
                     conecte.rs.getString("id_pac"),
                     conecte.rs.getString("nome_pac"),//pega do banco
                     conecte.rs.getString("idade_pac"),
                     conecte.rs.getString("cpf_pac"),
                     conecte.rs.getString("telefone_pac"), 
                     conecte.rs.getString("bairro")
                     
                 });
            }while(conecte.rs.next());//quando passar para o proximo para
             
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"Verifique se escreveu corretamente");
        }
        
        Table tab = new Table(dados, Colunas);

        jTablePac.setModel(tab);
        jTablePac.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTablePac.getColumnModel().getColumn(0).setResizable(false);
        jTablePac.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTablePac.getColumnModel().getColumn(1).setResizable(false);
        jTablePac.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTablePac.getColumnModel().getColumn(2).setResizable(false);
        jTablePac.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTablePac.getColumnModel().getColumn(3).setResizable(false);
        jTablePac.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTablePac.getColumnModel().getColumn(4).setResizable(false);
        jTablePac.getColumnModel().getColumn(5).setPreferredWidth(200);
        jTablePac.getColumnModel().getColumn(5).setResizable(false);


        jTablePac.getTableHeader().setReorderingAllowed(false);//não vai poder reorganizar as ordem das colunas
        jTablePac.setAutoResizeMode(jTablePac.AUTO_RESIZE_OFF);//O usuario não vai poder modificar o tamanho da tabela
        jTablePac.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//so vai poder selecionar um dado por vez

        conecte.desconecta();

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPacient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPacient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxBairro;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedCpf;
    private javax.swing.JFormattedTextField jFormattedTextTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMedico3;
    private javax.swing.JLabel jLabelMedico4;
    private javax.swing.JLabel jLabelSenha3;
    private javax.swing.JLabel jLabelSenha4;
    private javax.swing.JLabel jLabelSenha5;
    private javax.swing.JLabel jLabelcpf;
    private javax.swing.JLabel jLabelcpf1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePac;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JLabel quadro;
    // End of variables declaration//GEN-END:variables
}
