/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import ModelDao.DaoEnd;
import ModelDao.DaoEnd2;
import ModelDao.Table;
import conection.ConexaoBanco;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelBeans.ModelEnd;

/**
 *
 * @author kasil
 */
public class CadastroEndereco extends javax.swing.JFrame {

    ModelEnd mod = new ModelEnd();
    DaoEnd2 dao = new DaoEnd2();
    ConexaoBanco conecte = new ConexaoBanco();
    int flag = 0;
    
    public CadastroEndereco() {
        initComponents();
        atualizarTabela("select *from endereco order by logradouro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelBairro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelMedico3 = new javax.swing.JLabel();
        jButtonPaciente = new javax.swing.JButton();
        jTextLogradouro = new javax.swing.JTextField();
        jTextCasa = new javax.swing.JTextField();
        jTextBairro = new javax.swing.JTextField();
        jTextCidade = new javax.swing.JTextField();
        jTextiD = new javax.swing.JTextField();
        jLabelSenha5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        quadro = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 630, -1));

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, -1, -1));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, -1, -1));

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 620, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, -1, -1));

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1.png"))); // NOI18N
        jLabel1.setToolTipText("Cadastro de Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(172, 168, 238));

        jLabelBairro.setBackground(new java.awt.Color(0, 0, 0));
        jLabelBairro.setText("Bairro:");

        jLabel2.setText("ID:");

        jLabel3.setText("Logradouro:");

        jLabel4.setText("Nº da casa:");

        jLabel5.setText("Cidade:");

        jLabelMedico3.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMedico3.setText("Para fazer o cadastro do Paciente clique no botão abaixo:");

        jButtonPaciente.setText("Paciente");
        jButtonPaciente.setEnabled(false);
        jButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPacienteActionPerformed(evt);
            }
        });

        jTextLogradouro.setEnabled(false);

        jTextCasa.setEnabled(false);

        jTextBairro.setEnabled(false);

        jTextCidade.setEnabled(false);

        jTextiD.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCidade))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextiD, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonPaciente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMedico3, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTextLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextiD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBairro)
                        .addComponent(jTextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMedico3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPaciente)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 740, 190));

        jLabelSenha5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSenha5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha5.setText("Endereço:");
        getContentPane().add(jLabelSenha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 740, 140));

        quadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/maiorr.png"))); // NOI18N
        getContentPane().add(quadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Desktop - 19.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 740));

        setSize(new java.awt.Dimension(1380, 760));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int resposta = 0;
    //se o usuario quer realmente excluir
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if(resposta == JOptionPane.YES_OPTION){
            mod.setId_endereco(Integer.parseInt(jTextiD.getText()));
            dao.Excluir(mod);
            
            jTextiD.setText("");
            jTextBairro.setText("");
            jTextLogradouro.setText("");//limpa os campos
            jTextCasa.setText("");
            jTextCidade.setText("");
            
            atualizarTabela("select *from endereco order by logradouro");

            jButtonNovo.setEnabled(true);
            jButtonAlterar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonExcluir.setEnabled(false);
   
        
        }
        
        
        

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        
        jTextLogradouro.setEnabled(!true);
        jTextCasa.setEnabled(!true);
        jTextCidade.setEnabled(!true);//desativa os campos
        jTextBairro.setEnabled(!true);

        
        jButtonSalvar.setEnabled(false);//desativa o botao de salvar
        jButtonCancelar.setEnabled(false);
        
        jButtonNovo.setEnabled(true);
        
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
        jTextiD.setText("");
        jTextBairro.setText("");
        jTextLogradouro.setText("");//limpa os campos
        jTextCasa.setText("");
        jTextCidade.setText("");

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag = 2;
        jTextBairro.setEnabled(true);//ativa os campos
        jTextCidade.setEnabled(true);
        jTextCasa.setEnabled(true);
        jTextLogradouro.setEnabled(true);
        jButtonPaciente.setEnabled(true);
        
        jButtonSalvar.setEnabled(true);//ativa o botao de salvar
        jButtonCancelar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        
       /* atualizarTabela("select *from endereco order by bairro");*/
        
       // jFormattedCrm.setText("");
        
        
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        
       // jButtonCancelar.setEnabled(true);
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        
        if(jTextBairro.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Preencha o Bairro para continuar");// se for vazio avisará
           jTextBairro.requestFocus(); // para usuario ver o campo q falta
        }else if(jTextLogradouro.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha o Logradouro para continuar");
           jTextLogradouro.requestFocus();
        }else if(jTextCidade.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha sua Cidade para continuar");
           jTextCidade.requestFocus();
        }else if(jTextCasa.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Preencha o Nº da casa para continuar");
           jTextCasa.requestFocus();

        }else
        if(flag == 1){
           flag = 1;
           mod.setLogradouro(jTextLogradouro.getText());
           mod.setNum_casa(Integer.parseInt(jTextCasa.getText()));
           mod.setBairro(jTextBairro.getText());
           mod.setCidade(jTextCidade.getText());

           dao.Salvar(mod);

           jTextiD.setText("");
           jTextBairro.setText("");
           jTextLogradouro.setText("");//limpa os campos
           jTextCasa.setText("");
           jTextCidade.setText("");
        
           jButtonPaciente.setEnabled(true);
           jTextLogradouro.setEnabled(false);
           jTextCasa.setEnabled(false);
           jTextCidade.setEnabled(false);//desativa os campos
           jTextBairro.setEnabled(false);
        
           jButtonSalvar.setEnabled(false);
           jButtonCancelar.setEnabled(false);

           jButtonNovo.setEnabled(true);
        
           atualizarTabela("select *from endereco order by logradouro"); 
            
       }else{
           mod.setId_endereco(Integer.parseInt(jTextiD.getText()));
           mod.setLogradouro(jTextLogradouro.getText());
           mod.setNum_casa(Integer.parseInt(jTextCasa.getText()));
           mod.setBairro(jTextBairro.getText());
           mod.setCidade(jTextCidade.getText());
           
           dao.Alterar(mod);
           jButtonPaciente.setEnabled(true);
           jTextLogradouro.setEnabled(false);
           jTextCasa.setEnabled(false);
           jTextCidade.setEnabled(false);//desativa os campos
           jTextBairro.setEnabled(false);
           
           jButtonNovo.setEnabled(true);
           jButtonSalvar.setEnabled(false);
           
           jTextiD.setText("");
           jTextBairro.setText("");
           jTextLogradouro.setText("");//limpa os campos
           jTextCasa.setText("");
           jTextCidade.setText("");
           jTextFieldPesquisar.setText("");
           
           atualizarTabela("select *from endereco order by logradouro");
            
       }
       
       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        
        jTextLogradouro.setEnabled(true);
        jTextCasa.setEnabled(true);
        jTextCidade.setEnabled(true);//desativa os campos
        jTextBairro.setEnabled(true);
        
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldPesquisar.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        mod.setPesquisar(jTextFieldPesquisar.getText());
        ModelEnd model = dao.pesquisaEndereco(mod);
        
        jTextiD.setText(String.valueOf(model.getId_endereco()));
        jTextLogradouro.setText(model.getLogradouro());
        jTextCasa.setText(String.valueOf(model.getNum_casa()));
        jTextBairro.setText(model.getBairro());
        jTextCidade.setText(model.getCidade());

        jButtonPaciente.setEnabled(true);
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);        
        atualizarTabela("select *from endereco where logradouro like'%" + mod.getPesquisar()+"%'");
        
   
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPacienteActionPerformed
        CadastroPacient tela = new CadastroPacient();
        tela.setVisible(true);
    }//GEN-LAST:event_jButtonPacienteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String nomeUser = ""+jTable1.getValueAt(jTable1.getSelectedRow(),1);//oq for selecionado e vai colocar na string
        conecte.conexao();
        conecte.executaSql("select *from endereco where logradouro ='"+nomeUser+"'");
        try {
 
            if(conecte.rs.first()){//vai pegar o primeiro clique e vai verificar se é depois verifcar no banco se realmente tem esses dados
                
                jTextiD.setText(String.valueOf(conecte.rs.getInt("id_endereco")));
                jTextLogradouro.setText(conecte.rs.getString("logradouro"));
                jTextCasa.setText(String.valueOf(conecte.rs.getInt("num_casa")));
                jTextBairro.setText(conecte.rs.getString("bairro"));
                jTextCidade.setText(conecte.rs.getString("cidade"));
                //jPasswordConfirme.setText(conecte.rs.getString("login_id"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecioonar o dado"+ex);//caso de erro aparece uma mensagem
        }
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(true);//habilita botoes
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        conecte.desconecta();
    }//GEN-LAST:event_jTable1MouseClicked

    public void atualizarTabela(String SQL){
        //dados = new ArrayList(); 
        ArrayList dados = new ArrayList();      
        String[] Colunas = new String[]{"ID","Logradouro","Nº da casa", "Bairro", "Cidade"};//nome das colunas
        
        conecte.conexao();
        conecte.executaSql(SQL);
        
        try {
            conecte.rs.first();
             do{
                 dados.add(new Object[]{
                     
                     conecte.rs.getString("id_endereco"),
                     conecte.rs.getString("logradouro"),//pega do banco
                     conecte.rs.getString("num_casa"),
                     conecte.rs.getString("bairro"),
                     conecte.rs.getString("cidade")
                     
                 });
            }while(conecte.rs.next());//quando passar para o proximo para
             
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"Verifique se escreveu corretamente");
        }
        
        Table tab = new Table(dados, Colunas);

        jTable1.setModel(tab);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(170);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(180);
        jTable1.getColumnModel().getColumn(4).setResizable(false);

        jTable1.getTableHeader().setReorderingAllowed(false);//não vai poder reorganizar as ordem das colunas
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);//O usuario não vai poder modificar o tamanho da tabela
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//so vai poder selecionar um dado por vez

        conecte.desconecta();

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEndereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPaciente;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelMedico3;
    private javax.swing.JLabel jLabelSenha5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JTextField jTextCasa;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextLogradouro;
    private javax.swing.JTextField jTextiD;
    private javax.swing.JLabel quadro;
    // End of variables declaration//GEN-END:variables
}
