/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conection.ConexaoBanco;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kasil
 */
public class TelaPrincipall extends javax.swing.JFrame {

    ConexaoBanco conecta = new ConexaoBanco();
    CadastroMedico1 tela = new CadastroMedico1();
    CadastroUsuario user = new CadastroUsuario();
     
    public TelaPrincipall(String usuario) {
        initComponents();
        FUNCAO.setText(usuario);
        conecta.conexao();
    }

    private TelaPrincipall() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        usuario = new javax.swing.JButton();
        paciente = new javax.swing.JButton();
        medico = new javax.swing.JButton();
        agenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPainelFundo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JSairBemVindo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        FUNCAO = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenuItem();
        Paciente = new javax.swing.JMenuItem();
        jMenuMedico = new javax.swing.JMenuItem();
        ferramentas = new javax.swing.JMenu();
        jMenuTela = new javax.swing.JMenuItem();
        JSair = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setBackground(new java.awt.Color(48, 106, 160));
        jInternalFrame1.setForeground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setTitle("Bem- vindo");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cad.png"))); // NOI18N
        usuario.setToolTipText("Usuário");
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        jPanelInternal.add(usuario);
        usuario.setBounds(30, 70, 80, 70);

        paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mulher.png"))); // NOI18N
        paciente.setToolTipText("Paciente");
        paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteActionPerformed(evt);
            }
        });
        jPanelInternal.add(paciente);
        paciente.setBounds(130, 70, 80, 70);

        medico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/enfermeira.png"))); // NOI18N
        medico.setToolTipText("Médica");
        medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoActionPerformed(evt);
            }
        });
        jPanelInternal.add(medico);
        medico.setBounds(230, 70, 80, 70);

        agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backend.png"))); // NOI18N
        agenda.setToolTipText("Usuário");
        agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaActionPerformed(evt);
            }
        });
        jPanelInternal.add(agenda);
        agenda.setBounds(30, 200, 80, 70);

        jLabel1.setText("Cadastro");
        jPanelInternal.add(jLabel1);
        jLabel1.setBounds(30, 40, 60, 16);

        jLabel4.setText("Agendamentos");
        jPanelInternal.add(jLabel4);
        jLabel4.setBounds(30, 170, 110, 16);

        jPainelFundo.setBackground(new java.awt.Color(255, 255, 255));
        jPainelFundo.setForeground(new java.awt.Color(255, 255, 255));
        jPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_3.png"))); // NOI18N
        jPanelInternal.add(jPainelFundo);
        jPainelFundo.setBounds(0, 0, 1090, 390);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\UFC\\POO\\fundomaior.png")); // NOI18N
        jPanelInternal.add(jLabel2);
        jLabel2.setBounds(0, -50, 2219, 890);

        jInternalFrame1.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 60, 1090, 390);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sistema de gerenciamento de :");
        jInternalFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 300, 24);

        JSairBemVindo.setBackground(new java.awt.Color(230, 36, 36));
        JSairBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/off2.png"))); // NOI18N
        JSairBemVindo.setToolTipText("Sair da tela bem - vindo");
        JSairBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSairBemVindoActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(JSairBemVindo);
        JSairBemVindo.setBounds(800, 6, 40, 30);

        jLabel6.setText("Usuário:");
        jInternalFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 460, 60, 16);

        FUNCAO.setText("função");
        jInternalFrame1.getContentPane().add(FUNCAO);
        FUNCAO.setBounds(60, 460, 210, 16);

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 860, 510));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Desktop - 19.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1370, 740));

        jMenuBar1.setForeground(new java.awt.Color(7, 125, 93));

        cadastro.setIcon(new javax.swing.ImageIcon("D:\\UFC\\POO\\usuario.png")); // NOI18N
        cadastro.setText("Cadastrar");
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });

        jMenuUsuario.setText("Novo usuário");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        cadastro.add(jMenuUsuario);

        Paciente.setText("Pacientes");
        Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacienteActionPerformed(evt);
            }
        });
        cadastro.add(Paciente);

        jMenuMedico.setText("Médicos");
        jMenuMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMedicoActionPerformed(evt);
            }
        });
        cadastro.add(jMenuMedico);

        jMenuBar1.add(cadastro);

        ferramentas.setIcon(new javax.swing.ImageIcon("D:\\UFC\\POO\\construction-and-tools.png")); // NOI18N
        ferramentas.setText("Ferramentas");

        jMenuTela.setText("Tela bem-vindo");
        jMenuTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTelaActionPerformed(evt);
            }
        });
        ferramentas.add(jMenuTela);

        jMenuBar1.add(ferramentas);

        JSair.setIcon(new javax.swing.ImageIcon("D:\\UFC\\POO\\off.png")); // NOI18N
        JSair.setText("Sair");

        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        JSair.add(jMenuItem5);

        jMenuBar1.add(JSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1386, 785));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        try {
            conecta.executaSql("select *from caduser where nome_user='"+FUNCAO.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("Administrador")){
                CadastroUsuario user = new CadastroUsuario();
                user.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem acesso a essa funcionalidade, verifique com o Administrador");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem acesso a essa funcionalidade, verifique com o Administrador");
        }

    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cadastroActionPerformed

    private void jMenuTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTelaActionPerformed
        // TODO add your handling code here:
        jInternalFrame1.setVisible(true);
    }//GEN-LAST:event_jMenuTelaActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        conecta.desconecta();
        System.exit(0); //fecha o sistema geral
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteActionPerformed

        CadastroEndereco end = new CadastroEndereco();
        end.setVisible(true);
    }//GEN-LAST:event_pacienteActionPerformed

    private void JSairBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSairBemVindoActionPerformed
        // TODO add your handling code here:]
        jInternalFrame1.dispose();

    }//GEN-LAST:event_JSairBemVindoActionPerformed

    private void jMenuMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMedicoActionPerformed
        try {
            conecta.executaSql("select *from caduser where nome_user='"+FUNCAO.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("Administrador")){
                CadastroMedico1 tela = new CadastroMedico1();
                tela.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem acesso a essa funcionalidade, verifique com o Administrador");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem acesso a essa funcionalidade, verifique com o Administrador");
        }
    }//GEN-LAST:event_jMenuMedicoActionPerformed

    private void agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaActionPerformed
        Agendamento tela = new Agendamento();
        tela.setVisible(true);
    }//GEN-LAST:event_agendaActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        try {
            conecta.executaSql("select *from caduser where nome_user='"+FUNCAO.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("Administrador")){
                CadastroUsuario user = new CadastroUsuario();
                user.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem acesso a essa funcionalidade, verifique com o Administrador");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem acesso a essa funcionalidade, verifique com o Administrador");
        }
        
    }//GEN-LAST:event_usuarioActionPerformed

    private void medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoActionPerformed
        
        try {
            conecta.executaSql("select *from caduser where nome_user='"+FUNCAO.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("Administrador")){
                CadastroMedico1 tela = new CadastroMedico1();
                tela.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Você não tem acesso a essa funcionalidade, verique com o Administrador");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem acesso a essa funcionalidade, verique com o Administrador");
        }
        
    }//GEN-LAST:event_medicoActionPerformed

    private void PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacienteActionPerformed
        CadastroEndereco end = new CadastroEndereco();
        end.setVisible(true);
    }//GEN-LAST:event_PacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNCAO;
    private javax.swing.JMenu JSair;
    private javax.swing.JButton JSairBemVindo;
    private javax.swing.JMenuItem Paciente;
    private javax.swing.JButton agenda;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenu ferramentas;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuMedico;
    private javax.swing.JMenuItem jMenuTela;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JLabel jPainelFundo;
    private javax.swing.JPanel jPanelInternal;
    private javax.swing.JButton medico;
    private javax.swing.JButton paciente;
    private javax.swing.JButton usuario;
    // End of variables declaration//GEN-END:variables
}
